export const SEARCH_SERIES_SUCCESS = 'SEARCH_SERIES_SUCCESS';
export const SEARCH_SERIES_ERROR = 'SEARCH_SERIES_ERROR';

export const GET_SHOW_INFO_SUCCESS = 'GET_SHOW_INFO_SUCCESS';
export const GET_SHOW_INFO_ERROR = 'GET_SHOW_INFO_ERROR';